packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.63.13~ynh1"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    help.en = "Minimum length is 12"
    help.fr = "12 caractères minimum"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.13/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "1743269f00cf0f23f43e1a2e899beacb54d178092f8af992dc0d304fcf26556e"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.13/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "9baf1d903a721f5e74409bb04e883d91fed493bdc724f7baaa7ee663f832fbc7"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.13/linux-386-filebrowser.tar.gz"
        i386.sha256 = "f8f64d0b6df09226305cb07a3ac0b0873591145eba6335c624d0b3a6ed428dcd"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.13/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "4374daaf3291818859725f68bc51f48766b3b35e2df69a997e667e81468c6971"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
