packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.63.4~ynh1"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    help.en = "Minimum length is 12"
    help.fr = "12 caractères minimum"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.4/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "ba0eedcb8fe88a97703b610346635caaab1d6ae3ffccf004b520df6982451004"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.4/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "fbbec420e4b1c866e73f8699116bedfed9bc0acfe79dccae906dee746d633a40"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.4/linux-386-filebrowser.tar.gz"
        i386.sha256 = "becad17cc25feacd8ef0918e661a832a4bf78ab9d6c76f55ac1cf73998c848b1"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.63.4/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "bf90bb61311a0c80e8fe546e0337460b422f80fadceb64110357d440ec14664d"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
