packaging_format = 2

id = "filebrowser"
name = "Filebrowser"
description.en = "Web File Browser"
description.fr = "Gestionnaire de fichiers"

version = "2.61.1~ynh1"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://filebrowser.org"
admindoc = "https://filebrowser.org/"
code = "https://github.com/filebrowser/filebrowser"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filebrowser"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    help.en = "Minimum length is 12"
    help.fr = "12 caractères minimum"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.61.1/linux-amd64-filebrowser.tar.gz"
        amd64.sha256 = "601ac6c668e5e4524853073677547808dea074f46d4d7bd89529bd7de330a955"
        arm64.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.61.1/linux-arm64-filebrowser.tar.gz"
        arm64.sha256 = "39791d503d813607426f5882868b80ba4662ad11617b9cd186989c1d3f11c762"
        i386.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.61.1/linux-386-filebrowser.tar.gz"
        i386.sha256 = "260dad31ed3c356c11d1eb6210681c54614448749e37dd1a4346504a669c76fd"
        armhf.url = "https://github.com/filebrowser/filebrowser/releases/download/v2.61.1/linux-armv7-filebrowser.tar.gz"
        armhf.sha256 = "bc02d34d41de7a88cbd7fd3d5f08c4450d88a6bb056d157c2de206bfaf624a46"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^linux-amd64-filebrowser.tar.gz$"
        autoupdate.asset.arm64 = "^linux-arm64-filebrowser.tar.gz$"
        autoupdate.asset.i386 = "^linux-386-filebrowser.tar.gz$"
        autoupdate.asset.armhf = "^linux-armv7-filebrowser.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
